name: "CI"
on:
  pull_request:
  push:
    # Comment out this section to enable testing of all branches.
    branches:
      - master
jobs:
  gnu-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.3
          - 27.1
          - 27.2
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/setup-dotnet@v1
    - uses: actions/checkout@v2
    - uses: cask/setup-cask@master
    - name: Show dotnet sdks
      run: dotnet --list-sdks
    - name: Show dotnet version
      run: dotnet --info
    - name: Test
      run: make test
  windows-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/setup-dotnet@v1
    - uses: cask/setup-cask@master
    - name: Install scoop-emacs
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop update
        scoop bucket add extras
        scoop install emacs
        scoop install make
        echo "$env:PATH" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - uses: actions/checkout@v2
    - name: Test
      run: |
        dotnet restore test/Test1
        make test



